### ISSUE TITLE
terraform destroy errors on out

### ISSUE THREAD

**Issue by VannAtApollo** [apollosolutions/build-a-supergraph#34]
Intended outcome:  to have all of the resources created by terraform be completely removed. 

Actual outcome:  Here is the output from `terraform destroy`

`module.gcp-network["dev"].module.vpc.google_compute_network.network: Still destroying... [id=projects/vanns-demo/global/networks/apollo-supergraph-k8s-dev, 10s elapsed]
╷
│ Error: Error waiting for Deleting Network: The network resource 'projects/vanns-demo/global/networks/apollo-supergraph-k8s-dev' is already being used by 'projects/vanns-demo/zones/us-east1-b/networkEndpointGroups/k8s1-ddb447c6-router-router-80-9f63cdd9'

│ Error: Error waiting for Deleting Network: The network resource 'projects/vanns-demo/global/networks/apollo-supergraph-k8s-prod' is already being used by 'projects/vanns-demo/zones/us-east1-b/networkEndpointGroups/k8s1-c2594fb3-router-router-80-85833c8e'
│ `

How to recreate:  Follow the setup instructions until you run the checks demo.   Then run `terraform destroy`

**Comment by lleadbet** [comment]
Did you run the commands here: https://github.com/apollosolutions/build-a-supergraph/tree/main/06-cleanup#automated-cleanup

Running `terraform destroy` before those commands it can result in errors like the above.

**Comment by VannAtApollo** [comment]
Nope, I missed that step.  Thank you.
